### ISSUE TITLE
Демо или просто запущенный инстанс? 

### ISSUE THREAD

**Issue by samizdam** [Vehsamrak/optiontable#7]
А есть поднятый сайт с этим приложением?

**Comment by Vehsamrak** [comment]
@samizdam http://185.5.250.81

**Comment by samizdam** [comment]
Я, если честно, ничего не смыслю в этой машинерии, но как хорошо что там ни строчки js!  
Просто отдушина не лагающего, быстрого и валидного html ^_^

**Comment by Vehsamrak** [comment]
@samizdam с этим невозможно поспорить! :+1:
